#ifndef _RESOURCE_H_
#define _RESOURCE_H_

#define ID_PROCESS_INJECT_DLL 1001
#define ID_PROCESS_INJECT_RECENT_MENU 1002

#define ID_PROCESS_INJECT_RECENT_BASE 2000
#define ID_PROCESS_INJECT_RECENT_MAX 2020 // BASE + 20 (HISTORY_MAX_ENTRIES)
#define ID_PROCESS_INJECT_CLEAR_HISTORY 2030

#define IDD_OPTIONS 101

#define IDC_METHOD_COMBO 1101
#define IDC_METHOD_DESC 1102
#define IDC_TIMEOUT_EDIT 1103
#define IDC_TIMEOUT_SPIN 1104
#define IDC_CONFIRM_CHECK 1105
#define IDC_NOTIFY_CHECK 1106
#define IDC_HISTORY_EDIT 1107
#define IDC_HISTORY_SPIN 1108
#define IDC_CLEAR_HISTORY 1109
#define IDC_ERASE_CHECK 1110
#define IDC_UNLINK_CHECK 1111
#define IDC_HIDETHREAD_CHECK 1112

#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#endif // _RESOURCE_H_
